### ISSUE TITLE
Profile Checkout Approvals

### ISSUE THREAD

**Issue by pbnj** [britive/python-sdk#66]
The Britive API docs indicate [[0][]] it is possible to approve profile checkout requests, like so:

```
curl -X PATCH '{{url}}/api/v1/approvals/{approvalid}?approveRequest=yes/no' -H 'Authorization: Bearer <token>'
```

I could not find the appropriate method to do this via the Python SDK, but I could be missing it.

[0]: https://docs.britive.com/docs/manage-approvals#1-approvereject-a-request

**Comment by twratl** [comment]
i think this would be a feature enhancement. we support requesting approval via the cli/sdk but not providing the approval as of yet. will add it into the next release.

**Comment by twratl** [comment]
this has been incorporated into v2.19.0 which has just been published.
